# Generated by Django 4.0.6 on 2022-07-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='вид замка')),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.FileField(upload_to='images')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя юнита')),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.FileField(blank=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castle', to='HeroesWiki.castle')),
            ],
        ),
    ]
